import { deprecatedPropType } from "@mui/material";

const Constants = {

    SUCCESS_MESSAGE : {
        TYPE_USERLOGIN :        "SUC|001",
        TYPE_CREATE_NEW_USER :  "SUC|002",
        TYPE_EDIT_USER_DATA :   "SUC|003",
        TYPE_CHANGE_PASSWORD :  "SUC|004",
        TYPE_EDIT_REACTIVATE :  "SUC|005",
        TYPE_EDIT_DEACTIVATE :  "SUC|006",
        TYPE_REVIEWUS :         "SUC|007",
        TYPE_SEARCH_RESULTS :   "SUC|008",
        TYPE_SEND_FRIEND_REQUEST : "SUC|009",
        TYPE_SEND_FOLLOW_REQUEST : "SUC|010",
        TYPE_ACCEPT_FRIEND_REQUEST : "SUC|011",
        TYPE_ACCEPT_FOLLOW_REQUEST : "SUC|012",
        TYPE_REJECT_FRIEND_REQUEST : "SUC|013",
        TYPE_REJECT_FOLLOW_REQUEST : "SUC|014",
        TYPE_GET_FRIEND_LIST_REQUEST : "SUC|015",
        TYPE_GET_FOLLOW_LIST_REQUEST : "SUC|016",
        TYPE_GET_FRIEND_REQUEST_LIST_REQUEST : "SUC|017",
        TYPE_GET_FOLLOW_REQUEST_LIST_REQUEST : "SUC|018",
        TYPE_BLOCK_USER_REQUEST : "SUC|019",
        /** @deprecated Use TYPE_REJECT_FRIEND_REQUEST instead */
        TYPE_REMOVE_FRIEND_REQUEST : "SUC|020",
        /** @deprecated Use TYPE_REJECT_FOLLOW_REQUEST instead */
        TYPE_REMOVE_FOLLOW_REQUEST : "SUC|021",
        TYPE_GET_BLOCK_USER_LIST_REQUEST : "SUC|022",
        TYPE_FETCH_USER_DATA :  "SUC|023",
        TYPE_LOGOFF:            "SUC|024",
        TYPE_CONTACTSUPPORT :   "SUC|025"
    },

    ERROR_MESSAGE : {
        TYPE_ERROR_MESSAGE :    "ERR|001"
    }


};

export default Constants;